name: token_parser
description: An intuitive Token Parser that includes grammar definition, tokenization, parsing, syntax error and debugging. Implementation based on Lexical Analysis for Dart.
version: 1.5.2
repository: https://github.com/DrafaKiller/TokenParser-dart
issue_tracker: https://github.com/DrafaKiller/TokenParser-dart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
