name: token_parser
description: An intuitive Token Parser that includes syntax/grammar definition, tokenization and parsing. Implementation based on Lexical Analysis.
version: 0.0.1+1
repository: https://github.com/DrafaKiller/TokenParser-dart
issue_tracker: https://github.com/DrafaKiller/TokenParser-dart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
